#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 16
#SBATCH -C cpu
# Note: to use this QOS, your PI or PI Proxy needs to grant you access
#SBATCH -q regular
#SBATCH -J Pathline
#SBATCH --mail-user=chen.10522@osu.edu
#SBATCH --mail-type=ALL
#SBATCH -A m4259
#SBATCH -t 6:0:0

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
time srun -n 256 -c 16 --cpu_bind=cores  ./ParaFlow_pathline conf/nersc_lowres_pathline.yaml
